# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UTrend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UTrend
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'FirebaseUI'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'GoogleSignIn'
pod 'Firebase/Storage'

end
